[package]
name = "kuali-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
# Used by internal button responses and @username resolution.
tokio = { workspace = true }
toml.workspace = true
uuid.workspace = true
